# Project information
site_name: Christmas Countdown
site_description: Documentation for Christmas Countdown website, Discord bot, and API.
site_author: eartharoid
site_url: https://docs.christmascountdown.live

# Repository
repo_name: christmas-countdown/docs
repo_url: https://github.com/christmas-countdown/docs
edit_uri: blob/master/docs/

# Copyright
copyright: '&copy; 2020 Isaac Saunders'

# Configuration
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    - javascripts/extra.js

theme:
  name: material
  language: en

  custom_dir: overrides/
  
  palette:
    scheme: custom
    primary: primary
    accent: primary

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand

  logo: /img/logo.png
  favicon: /img/favicon.ico

# Extras
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://www.christmascountdown.live
    - icon: fontawesome/brands/github-alt
      link: https://github.com/eartharoid
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eartharoid
  discord: https://go.eartharoid.me/discord # {{ discord }} in md

# Google Analytics
#google_analytics:
#  - UA-XXXXXXXX-X
#  - auto

plugins:
  - search # necessary for search to work
  - git-revision-date-localized # last modified date at bottom of page
  - awesome-pages # custom nav order
  - macros

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
