# Project information
site_name: Christmas Countdown Docs
site_description: Documentation for Christmas Countdown projects.
site_author: eartharoid
site_url: https://docs.christmascountdown.live

# Repository
repo_name: eartharoid/ChristmasCountdown
repo_url: https://github.com/earhtaroid/christmascountdown

# Copyright
copyright: '&copy; 2020 Isaac Saunders'

# Configuration
theme:
  name: material
  custom_dir: overrides/
  language: en
  palette:
    scheme: default
    primary: red
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant
  logo: /img/logo.png
  favicon: /img/favicon.ico

# Extras
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://eartharoid.me
    - icon: fontawesome/brands/github-alt
      link: https://github.com/eartharoid
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eartharoid

# Google Analytics
#google_analytics:
#  - UA-XXXXXXXX-X
#  - auto

plugins:
  - search # necessary for search to work
  - git-revision-date-localized # last modified date at bottom of page
  - awesome-pages # custom nav order
  - tabs
  - navigation.expand

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
# pymd
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
